# Generated by Django 2.1.5 on 2019-01-20 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicewithfeepage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicewithfeepage',
            old_name='price',
            new_name='fee_price',
        ),
    ]
