# Generated by Django 2.1.5 on 2019-01-20 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20190120_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpage',
            name='service',
        ),
    ]
